name: Paul' Blog
description: 有了钱，在这个世界上可以做很多事，就是无法用钱来买青春
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: rouge
permalink: /blog/post/:title.html
logo: false
comments: true
paginate: 10
baseurl: /
domain_name: 'http://chztv.com'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'http://chztv.github.io/'
author:         'Paul chan'
